# Generated by Django 4.0.2 on 2022-02-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_call_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
