# Generated by Django 4.0.2 on 2022-02-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_remove_question_tags_question_level_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(max_length=20),
        ),
    ]
