# Generated by Django 4.0.2 on 2022-02-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
