# Generated by Django 4.0.2 on 2022-02-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_reply_answer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reply',
            constraint=models.UniqueConstraint(fields=('question', 'helper'), name='unique_question_helper'),
        ),
    ]
