# Generated by Django 4.0.2 on 2022-02-05 20:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(), size=None)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
