# Generated by Django 4.0.2 on 2022-02-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helper',
            name='rating',
        ),
    ]
